accounts/urls.py
from django.conf.urls import url
from .views import *



app_name = "accounts"

urlpatterns = [

    url(r'^$', HomeView.as_view(), name='home'),        
    url(r'^register/$', RegistrationView.as_view(), name='registration'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^forgotpassword/$', PasswordForgotView.as_view(), name='passwordforgot'),   
    url(r'^resetpassword/<email>/<token>/', PasswordResetView.as_view(), name="passwordreset"),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),

    url(r'^contact/$', ContactView.as_view(), name='contact'),

]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),

]
if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

accounts/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Customer(models.Model): 
    user = models.OneToOneField(User, on_delete=models.CASCADE)   # One customer is one user
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=250, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

accounts/forms.py
from django import forms
from .models import Customer
from django.contrib.auth.models import User

# Customer registration form


class RegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.CharField(widget=forms.EmailInput())

    class Meta:   # Form fields based by Models
        model = Customer
        fields = ['username', 'password', 'email', 'full_name', 'address']
   
    # If username matched existing user error will Rise
    def clean_username(self):
        uname = self.cleaned_data.get('username')
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError(
                "This username is already exists! try unique.")
        return uname 
    
    # If gmail matched existing user error will Rise
    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                "Customer with this email already exists.")

        return email

    # If email not gmail.com error will Rise(example as gmail)
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not 'gmail.com' in email:
            raise forms.ValidationError('Email has to be gmail.com')
        return email



class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())



class PasswordForgotForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={
        "class": "form-control",
        "placeholder": "Enter the email used in customer account..."
    }))

    def clean_email(self):
        e = self.cleaned_data.get("email")              # check Customer account exist or not 
        if Customer.objects.filter(user__email=e).exists():
            pass
        else:
            raise forms.ValidationError(
                "Customer with this account does not exists..")
        return e


class PasswordResetForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Enter New Password',
    }), label="New Password")
    confirm_new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Confirm New Password',
    }), label="Confirm New Password")

    def clean_confirm_new_password(self):
        new_password = self.cleaned_data.get("new_password")
        confirm_new_password = self.cleaned_data.get("confirm_new_password")
        if new_password != confirm_new_password:
            raise forms.ValidationError(
                "New Passwords did not match!")
        return confirm_new_password

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect 
from django.views.generic import View, TemplateView, CreateView, FormView
from .models import *
from django.urls import reverse_lazy
from .forms import RegistrationForm, LoginForm, PasswordForgotForm, PasswordResetForm 
from django.contrib.auth import authenticate, login, logout
# For password reset
from .utils import password_reset_token
from django.core.mail import send_mail

from django.conf import settings





# Create your views here.

# Class Based View
 
class HomeView(TemplateView):
    template_name = "home.html"



class RegistrationView(CreateView):
    template_name = "accounts/registration.html"
    form_class = RegistrationForm
    success_url = reverse_lazy('accounts:home')

    # form handle to create User
    def form_valid(self, form):  # Form_valid method is more robust then other methods
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        email = form.cleaned_data.get('email')
        user = User.objects.create_user(username, email, password)
        form.instance.user = user
        login(self.request, user)      # Instant Login after registration
        return super().form_valid(form)


class LogoutView(View):
    def get(self, request):      # request for logout and logout
        logout(request)
        return redirect("accounts:home")


class LoginView(FormView):
    template_name = "accounts/login.html"
    form_class = LoginForm
    success_url = reverse_lazy('accounts:home')
   
    #form_valid method is a type of post method, here used for authentic user
    def form_valid(self, form):
        uname = form.cleaned_data.get("username")
        pword = form.cleaned_data["password"]
        usr = authenticate(username=uname, password=pword)
        if usr is not None and Customer.objects.filter(user=usr).exists():
            login(self.request, usr)
        else:
            return render(self.request, self.template_name, {"form": self.form_class, "error": "Invalid credentials!"})

        return super().form_valid(form)



class ProfileView(TemplateView):
    template_name = "accounts/profile.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and Customer.objects.filter(user=request.user).exists():
            pass 
        else:
            return redirect('/login/?next=/profile/')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        customer = self.request.user.customer 
        context['customer'] = customer 
        return context 



class PasswordForgotView(FormView):
    template_name = "accounts/forgotpassword.html"
    form_class = PasswordForgotForm
    success_url = "/forgotpassword/?m=s"

    def form_valid(self, form):
        # get email from user
        email = form.cleaned_data.get("email")
        # get current host ip/domain
        url = self.request.META['HTTP_HOST']
        # get customer and then user
        customer = Customer.objects.get(user__email=email)
        user = customer.user
        # send mail to the user with email
        text_content = 'Please Click the link below to reset your password. '
        html_content = url + "/resetpassword/" + email + \
            "/" + password_reset_token.make_token(user) + "/"
        send_mail(
            'Password Reset Link | Django Ecommerce',
            text_content + html_content,
            settings.EMAIL_HOST_USER,
            [email],
            fail_silently=False,
        )
        return super().form_valid(form)


class PasswordResetView(FormView):
    template_name = "passwordreset.html"
    form_class = PasswordResetForm
    success_url = "/login/"

    def dispatch(self, request, *args, **kwargs):
        email = self.kwargs.get("email")
        user = User.objects.get(email=email)
        token = self.kwargs.get("token")
        if user is not None and password_reset_token.check_token(user, token):
            pass
        else:
            return redirect(reverse("accounts:passworforgot") + "?m=e")

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        password = form.cleaned_data['new_password']
        email = self.kwargs.get("email")
        user = User.objects.get(email=email)
        user.set_password(password)
        user.save()
        return super().form_valid(form)



class ContactView(TemplateView):   # About View

    template_name = 'contact.html'

templates/accounts/forgotpassword.html
{% extends 'base.html' %}

{% block title %}Forgot password{% endblock %}

{% block content %}
<div class="container mt-4 mb-4 ">
    <div class="row">
        <div class="col-md-8">
            {% if request.GET.m == "s" %}
            <h3>Password reset link is sent to your email address. Please check your email immediately. </h3>
            {% else %}
            <h3>Enter your email used in making customer account to get password reset link</h3>
            {% if request.GET.m == "e" %}
            <h4 class="text-danger">Something went wrong, please enter your email again.</h4>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button> Get Reset Link</button>
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}

Login Page

{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3 class="mt-4 mb-4">Customer Login Form</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary mb-4">Login as a Customer</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
            <p>Forgot Password?<a href="{% url 'accounts:passwordforgot' %}">Reset now.</a></p>
            <p> or dont have account? <a href="{% url 'accounts:registration' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Register here</a></p>

            <p> If you are admin  <a href="{% url 'accounts:login' %}">Admin Login here</a></p>    

        </div>
    </div>
</div>

{% endblock %}

templates/accounts/passwordreset.html
{% extends 'base.html' %}

{% block title %}Reset password{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button>Reset password</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}
My Profile
{% endblock %}

{% block content %}
   
    
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Detail Information</h3><hr>
            <p><span class="font-weight-bold">Name: </span> {{customer.full_name}}</p>
            <p><span class="font-weight-bold">Username: </span> {{customer.user.username}}</p>
            <p><span class="font-weight-bold">Email: </span> {{customer.user.email}}</p>
            <p><span class="font-weight-bold">Address: </span> {{customer.address}}</p>
            <p><span class="font-weight-bold">Joined on: </span> {{customer.joined_on}}</p>
        </div>
    </div>  
</div>  

{% endblock %}

templates/accounts/registration.html
{% extends 'base.html' %}

{% block title %}

Registration Page

{% endblock %}

{% block content %}
   
        <div class="container mt-4 mb-4">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <h3 class="mt-4 mb-4">Customer Registration Form</h3>
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class="btn btn-primary">Register as a Customer</button>
                    </form>
                    <p class="mt-4 mb-4"> Already have an account? <a href="{% url 'accounts:login' %}">Login here</a></p>
                </div>
            </div>
        </div>
        

{% endblock %}