accounts/urls.py
from django.conf.urls import url
from .views import *



app_name = "accounts"

urlpatterns = [

    url(r'^$', HomeView.as_view(), name='home'),        
    url(r'^register/$', RegistrationView.as_view(), name='registration'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^forgotpassword/$', PasswordForgotView.as_view(), name='passwordforgot'),   
    url(r'^resetpassword/<email>/<token>/', PasswordResetView.as_view(), name="passwordreset"),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),

    url(r'^contact/$', ContactView.as_view(), name='contact'),

]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),

]
if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="/">Our Site</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
           
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:contact' %}">Contact</a>
            </li>
            <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if request.user.customer %}
                     {{request.user.username}}
                <a class="dropdown-item" href="{% url 'accounts:profile' %}">My Profile</a>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'accounts:registration' %}">Register</a>
                <a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a>
                {% endif %}
                </div>
            </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="#" method="GET">
            <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
            <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        </nav>

   
    {% block content %}
    {% endblock %}



    <div class="jumbotron text-center bg-info mt-4" style="margin-bottom:0">
        <p> eCommerce Support </p>

        <p>Copyright 2021</p>
      </div>
      

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}

{% block title %}

Contact Page

{% endblock %}

{% block content %}




{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}

Home Page

{% endblock %}

{% block content %}



{% endblock %}